### ISSUE TITLE
TypeError: this.input.removeListener is not a function

### ISSUE THREAD

**Issue by soulshake** [yaronn/wopr#10]
Note: Contrary to #9, here I'm installing with `npm install` instead of specific versions of the dependencies.
### What I do

```
$ git clone https://github.com/yaronn/wopr.git /src/wopr
$ cd /src/wopr
$ npm install
$ node server.js
```

Then I run `curl -N localhost:1337/\[0-2\]\?auto\&cols=$((COLUMNS))` from the client.
### What I expect

The server should display those sweet-looking dashboards.
#### Client-side output

No dashboard appears, only this:

```
[1/3]: localhost:1337/0?auto&cols=94 --> <stdout>
--_curl_--localhost:1337/0?auto&cols=94
```

Then, a few seconds later:

```
[2/3]: localhost:1337/1?auto&cols=94 --> <stdout>
--_curl_--localhost:1337/1?auto&cols=94
curl: (7) Failed to connect to localhost port 1337: Connection refused

[3/3]: localhost:1337/2?auto&cols=94 --> <stdout>
--_curl_--localhost:1337/2?auto&cols=94
curl: (7) Failed to connect to localhost port 1337: Connection refused
```
#### The server-side logs:

```
Server running at http://127.0.0.1:1337/
TypeError: this.input.removeListener is not a function
    at Program.destroy (/src/wopr/node_modules/blessed/lib/program.js:487:18)
    at clean (/src/wopr/server/presenter.js:72:18)
    at null._onTimeout (/src/wopr/server/presenter.js:57:9)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
/src/wopr/node_modules/blessed/lib/program.js:487
      this.input.removeListener('keypress', this.input._keypressHandler);
                 ^

TypeError: this.input.removeListener is not a function
    at Program.destroy (/src/wopr/node_modules/blessed/lib/program.js:487:18)
    at Screen.destroy (/src/wopr/node_modules/blessed/lib/widgets/screen.js:442:16)
    at /src/wopr/node_modules/blessed/lib/widgets/screen.js:239:14
    at Array.forEach (native)
    at process.on.Screen._exitHandler (/src/wopr/node_modules/blessed/lib/widgets/screen.js:238:30)
    at emitOne (events.js:95:20)
    at process.emit (events.js:182:7)
    at process.exit (node.js:721:17)
    at Immediate._onImmediate (/src/wopr/node_modules/blessed/lib/widgets/screen.js:221:15)
    at processImmediate [as _immediateCallback] (timers.js:516:17)
```

**Comment by yaronn** [comment]
@soulshake - same here, you can try now

**Comment by soulshake** [comment]
Works now, thanks!
